services:
  app:
    image: ghcr.io/plobli/coworking-gast-zugangssystem:latest
    container_name: coworking-gast-zugangssystem
    restart: unless-stopped
    env_file:
      - config/.env
    volumes:
      - storage:/var/www/storage
    networks:
      - web
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --label-enable --cleanup
    environment:
      - WATCHTOWER_LABEL_ENABLE=true

networks:
  web:
    external: true

volumes:
  storage:
