services:
  app:
    image: ghcr.io/plobli/coworking-gast-zugangssystem:latest
    container_name: coworking-gast-zugangssystem
    restart: unless-stopped
    env_file:
      - config/.env
    volumes:
      - storage:/var/www/storage

volumes:
  storage:
